"""How well the indicator's entries line up with the zone it published.

The scanner draws an entry zone and then says "enter now". This asks
whether those two agreed: was price actually in the zone when the signal
fired, did the signal beat price there, or had price already passed
through? And when the signal was early, did price ever arrive at all.

Separated by direction, since a buy chasing upward and a sell chasing
downward are different mistakes with different causes.

    python entry_accuracy.py
"""
from __future__ import annotations

from typing import Any, Dict, List

import outcome_tracker as ot

LABELS = {
    ot.PLACEMENT_IN: 'in the zone',
    ot.PLACEMENT_BEFORE: 'before price reached the zone',
    ot.PLACEMENT_AFTER: 'after price passed the zone',
}


def _r_multiple(row: Dict[str, Any]):
    outcome = row.get('outcome')
    entry, stop = row.get('entry'), row.get('stop')
    if not outcome or outcome == ot.OUTCOME_OPEN or entry is None or stop is None:
        return None
    risk = abs(float(entry) - float(stop))
    if risk <= 0:
        return None
    if outcome == ot.OUTCOME_STOP:
        return -1.0
    if outcome == ot.OUTCOME_EXPIRED:
        return 0.0
    target = (row.get('targets') or {}).get(outcome)
    return None if target is None else abs(float(target) - float(entry)) / risk


def analyse(directory=None) -> Dict[str, Any]:
    # Live rows only: replayed setups are generated by entering at the zone
    # by construction, so including them would report the replay's design
    # rather than the indicator's timing.
    rows = [r for r in ot.load_signals(directory)
            if r.get('source') != 'historical' and r.get('placement')]
    out: Dict[str, Any] = {'total': len(rows), 'by_direction': {}}
    for direction in ('BUY', 'SELL'):
        subset = [r for r in rows if r.get('direction') == direction]
        buckets: Dict[str, List[Dict[str, Any]]] = {}
        for row in subset:
            buckets.setdefault(row['placement'], []).append(row)
        out['by_direction'][direction] = {'n': len(subset), 'buckets': buckets}
    return out


def report(directory=None) -> str:
    data = analyse(directory)
    lines = [f'Entry placement against the published zone  ({data["total"]} live signals)', '']
    if not data['total']:
        lines.append('No live signals carry zone data yet. Only signals logged after')
        lines.append('this was added record it, so the count starts from now.')
        return '\n'.join(lines)

    for direction in ('BUY', 'SELL'):
        block = data['by_direction'][direction]
        lines.append(f'{direction}  ({block["n"]} signals)')
        if not block['n']:
            lines.append('   none yet')
            lines.append('')
            continue
        for key in (ot.PLACEMENT_IN, ot.PLACEMENT_BEFORE, ot.PLACEMENT_AFTER):
            group = block['buckets'].get(key, [])
            share = 100 * len(group) / block['n']
            line = f'   {LABELS[key]:34s} {len(group):4d}  {share:5.1f}%'
            rs = [r for r in (_r_multiple(g) for g in group) if r is not None]
            if rs:
                wins = sum(1 for r in rs if r > 0)
                line += f'   mean {sum(rs)/len(rs):+.3f}R  won {100*wins/len(rs):.0f}%'
            lines.append(line)

            # For early entries, whether price ever arrived says whether
            # waiting would have been possible at all.
            if key == ot.PLACEMENT_BEFORE and group:
                reached = [g for g in group if g.get('zone_reached_bars')]
                if reached:
                    bars = [g['zone_reached_bars'] for g in reached]
                    lines.append(f'      price later reached the zone in {len(reached)}/{len(group)}'
                                 f', median {sorted(bars)[len(bars)//2]} candles')
                else:
                    lines.append(f'      price never returned to the zone in any of the {len(group)}')
        lines.append('')

    lines.append('A buy is "before" when taken above the zone, a sell when taken below it:')
    lines.append('in both cases the signal fired ahead of price reaching the level it named.')
    return '\n'.join(lines)


if __name__ == '__main__':
    print(report())
